services:
  proxy:
    image: nginx:latest
    ports:
      - "443:443"
      - "80:80"
    restart: always
    volumes:
      - ./backend/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./backend/nginx/nginx_certificates:/etc/nginx/nginx_certificates:ro

  server1:
    build: .
    ports:
      - 3000:${OPEN_PORT}  # computer-port:container-port (exposed)
    restart: always
    environment:
      - REPLICA_NAME=Marina

  server2:
    build: .
    ports:
      - 3001:${OPEN_PORT}
    restart: always
    environment:
      - REPLICA_NAME=Jessica

  server3:
    build: .
    ports:
      - 3002:${OPEN_PORT}
    restart: always
    environment:
      - REPLICA_NAME=Leon
